### ISSUE TITLE
it is not possible to ssh-copy-id on a diffrent port

### ISSUE THREAD

**Issue by fskaikaito** [n8tg/ssh-copy-id#1]
let say i have a server running ssh on port 2222

ssh-copy-id  doest not allow me to copy my pub key to that diffrent port
or did i missed something ?

ssh-copy-id "-p2222 root@212.124.10.81"  
result: not working
ssh-copy-id  root@212.124.10.81 -p2222 
result: not working 

the above ips are dummy ips.

**Comment by n8tg** [comment]
You're right, there isn't support for the port flag at the moment.

~~As a work around, you should be able to use the colon syntax for the remote address to specify the port to use. e.g. `root@212.123.10.81:2222`~~

I'll work on adding this, thanks for the suggestion!

Edit:
_I was wrong, I don't think the colon syntax will work. I'll keep you updated :)_
